### ISSUE TITLE
Suggestion: Fabric support

### ISSUE THREAD

**Issue by MeditatorLogic** [getItemFromBlock/Create-Tweaked-Controllers#17]
Well as the title has desbribed, more and more parts of the _Project Clockwork_ have been output into fabric 1.20.1 or so, as for convenience, will this be adapted as well?

**Comment by getItemFromBlock** [comment]
Well, this was asked multiple times already and the answer is that having support for Fabric is not that easy, since it requires rewriting some parts of the mod and also requires me to publish twice the amount of updates.
Now if you take a closer look at this pull request, you can see that Fabric support is partially on the way:
[https://github.com/getItemFromBlock/Create-Tweaked-Controllers/pull/16](https://github.com/getItemFromBlock/Create-Tweaked-Controllers/pull/16)
Keep in mind that there is quite a lot of work left to do
