### ISSUE TITLE
Allow deadzone config for controller

### ISSUE THREAD

**Issue by zackadiax24** [getItemFromBlock/Create-Tweaked-Controllers#29]
My (and many others) controller stick likes to drift from 1 to -1. I tried turning on custom mappings to mess with the deadzone settings only to discover that with custom mappings on i can map the buttons of my controller.

If possible the option to set deadzones without custom mappings on, or at the very least the ability to define a normal controller's mapping in the custom mapping menu would be appreciated.

**Comment by getItemFromBlock** [comment]
The advanced mode/custom mapping mode (which will probably become the default in a future update) have an option where you can put a minimum and maximum value for each axis. There is a page for that in the wiki.
Note however that I do plan to have a "per joystick" deadzone setting.
Also, if I make the advanced mode become the default, the mod will automatically fills in the inputs accordingly to the device you use.
My plan is to make it so that people installing the mod have little to no things to change, as opposed to right now.

**Comment by getItemFromBlock** [comment]
The actual default input mode will still stay for backward compatibility, but it will not be the recommended option anymore

**Comment by zackadiax24** [comment]
The issue i was having was that it wasn't registering my gamepad as a device for the custom mapping, but it worked normally.

**Comment by getItemFromBlock** [comment]
I am not sure to understand correctly, are you telling me that the controller works in simple mode, but you cannot bind it in advanced mode ? If that's the case then that would be the first time I see something like that, and to be honest I don't even know how that would be possible since GLFW is not supposed to do that

**Comment by getItemFromBlock** [comment]
In order to clean things up and don't leave stall issues, I will keep this as a feature/enhancement request.
A better system for handling deadzones will be added in a future update

**Comment by zackadiax24** [comment]
Not trying to necro the the thread or anything, but a decent solution to making it work a little better is to put 2 pieces of redstone dust between the link and whatever your activating.

it adds a small buffer to help account for your deadzone.
