### ISSUE TITLE
Suggestion: compatibility with Ranged Wireless Redstone

### ISSUE THREAD

**Issue by likeproblem** [getItemFromBlock/Create-Tweaked-Controllers#8]
I really like making small redstone builds, but constantly redirecting from redstone links to RWR is just sometimes annoying(I'm making a tank and there is no space for redirecting them).

**Comment by getItemFromBlock** [comment]
I see, the main problem is that this would need to be a Create mod compat, because my mod is directly using Create's existing system.
Now for this kind of stuff (like tank controls) I usually make it with CC tweaked, where the computer will translate the tweaked controller inputs via the peripheral provided by my mod, and use them to control the whole tank.

**Comment by likeproblem** [comment]
> Now for this kind of stuff (like tank controls) I usually make it with CC tweaked, where the computer will translate the tweaked controller inputs via the peripheral provided by my mod, and use them to control the whole tank.

Thanks for idea! I also have Project Red, so I could use bundled cables to easily transfer redstone across tank

**Comment by getItemFromBlock** [comment]
I think there is not really anything I can do more here, if this is really something you think would be useful, you should try to do a similar suggestion to the Create mod repository.
